- name: Ensure a server is a domain controller
  win_domain_controller:
    dns_domain_name: "{{ adds_domain_name }}"
    domain_admin_user: "{{ adds_ad_domadmin }}"
    domain_admin_password: "{{ adds_ad_dompass }}"
    safe_mode_password: "{{ adds_ad_dompass }}"
    state: domain_controller
    log_path: C:\ansible_win_domain_controller.txt
  register: domain_state

- name: Reboot if required
  win_reboot: 
  when: domain_state.reboot_required

- name: Change TimeZone
  win_timezone:
    timezone: Eastern Standard Time
    register: time