---
- hosts: addscreate
  gather_facts: no
  roles:
    - win_adds_create
  vars_files:
    - group_vars/variables.yml

- hosts: adds
  gather_facts: no
  roles:
   - win_adds_join
  vars_files:
   - group_vars/variables.yml